permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: wonderfan
  email: phpjavaphp@gmail.com
  link: http://www.wonderfan.net
  weibo: http://weibo.com/phpjavaphp
  github: http://github.com/wonderfan

# 站点信息
title: wonderfan的博客 
description: wonderfan的博客
url: http://www.wonderfan.net
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://wonderfan.gitgub.io/logo.png
favicon: http://wonderfan.github.io/favicon.ico

# google analytics 设置
ga:
  id: UA-xxxxxx
  url: http://www.wonderfan.net

# disqus 设置
disqus:
  shortname: wonderfan2000

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 博主
  newest: 最新文章
  archive: 归档
  content: 目录
