permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

author: 
  name:  wonderfan
  email: phpjavaphp@gmail.com
  link:  http://wonderfan.github.io
  weibo: http://weibo.com/phpjavaphp
  github: http://github.com/wonderfan

title: wonderfan的博客 
description: wonderfan的博客
url: http://wonderfan.github.io
rss_url: /pages/atom.xml

gavatar: http://www.wonderfan.github.io/logo.png
favicon: http://www.wonderfan.github.io/favicon.ico

ga:
  id: UA-56789989-1
  url: http://www.wonderfan.net

disqus:
  shortname: wonderfan2000


active: 中文

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 博主
  newest: 最新文章
  archive: 归档
  content: 目录
